server {
    listen 4200;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Servir les fichiers statiques
    location / {
        try_files $uri $uri/ /index.html;
    }
}
